# -*- coding: utf-8 -*-
"""epileptic_seizure_detection_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eiHk_J5d_5JYUHAPFoTHKuCF7E6q4eH5
"""

# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import class_weight
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
from tensorflow.keras.layers import Dense, Embedding
import seaborn as sns
from tensorflow.keras.layers import Input, Concatenate
from tensorflow.keras import Model
from sklearn.decomposition import PCA
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv('/content/Epileptic Seizure Recognition.csv')
df.head()

# Drop the 'Unnamed' column, which isn't necessary for the model
df = df.drop(columns=['Unnamed'], errors='ignore')

# Convert the multiclass labels to binary labels (1 = seizure, 0 = non-seizure) as levels 2, 3, 4, 5 are non epileptic
df['y'] = df['y'].apply(lambda x: 1 if x == 1 else 0)

# Separate features and labels
X = df.drop(columns=['y']).values  # Features (input EEG signals)
y = df['y'].values  # Labels (0 = non-seizure, 1 = seizure)

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Print the shape of the scaled features
print(f"Scaled features shape: {X_scaled.shape}")

# Split data into training and testing sets for LSTM (no windows, full dataset)
X_train_full, X_test_full, y_train_full, y_test_full = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Split the dataset into train and test sets first
X_train_full, X_test_full, y_train_full, y_test_full = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Function to create time series windows for CNN
def create_time_series_windows(X, y, window_size=10, step_size=1):
    X_windows = []
    y_windows = []

    for i in range(0, len(X) - window_size, step_size):
        X_windows.append(X[i:i + window_size, :])
        y_windows.append(y[i + window_size - 1])  # Label for the window is the last element in the window

    return np.array(X_windows), np.array(y_windows)

# Define window size and step size for CNN
window_size = 10
step_size = 1

# Create time series windows for CNN (only use the training set here)
X_train_windows, y_train_windows = create_time_series_windows(X_train_full, y_train_full, window_size, step_size)
X_test_windows, y_test_windows = create_time_series_windows(X_test_full, y_test_full, window_size, step_size)

# Compute class weights to handle class imbalance
class_weights = class_weight.compute_class_weight(class_weight='balanced', classes=np.unique(y), y=y)
class_weights_dict = {i: class_weights[i] for i in range(len(class_weights))}
print("Class weights:", class_weights_dict)

# LSTM Branch (Full dataset without windows)
lstm_input = layers.Input(shape=(X_train_full.shape[1],))  # Shape of full dataset (no time-series windows)
lstm_branch = layers.Reshape((X_train_full.shape[1], 1))(lstm_input)  # Reshape for LSTM input
lstm_branch = layers.LSTM(48)(lstm_branch)  # Reduced LSTM units slightly
lstm_branch = layers.Dropout(0.35)(lstm_branch)  # Increased dropout slightly

# CNN Branch (Time-series windows)
cnn_input = layers.Input(shape=(X_train_windows.shape[1], X_train_windows.shape[2]))  # Time-series window shape
cnn_branch = layers.Conv1D(24, kernel_size=3, activation='relu')(cnn_input)  # Reduced filters slightly
cnn_branch = layers.MaxPooling1D(pool_size=2)(cnn_branch)
cnn_branch = layers.Dropout(0.35)(cnn_branch)  # Increased dropout slightly
cnn_branch = layers.Flatten()(cnn_branch)

# Merge LSTM and CNN branches
merged = layers.Concatenate()([lstm_branch, cnn_branch])

# Dense layers after merging
merged = layers.Dense(48, activation='relu')(merged)  # Reduced number of units slightly
merged = layers.Dropout(0.35)(merged)  # Increased dropout slightly
output = layers.Dense(1, activation='sigmoid')(merged)  # Final output layer

# Create the hybrid model
model = models.Model(inputs=[lstm_input, cnn_input], outputs=output)

# Compile the model with a slightly smaller learning rate
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Trim the dataset to match the windowed data size (important step!)
X_train_full_trimmed = X_train_full[:X_train_windows.shape[0]]
X_test_full_trimmed = X_test_full[:X_test_windows.shape[0]]

# Now train the model with matching data sizes
history = model.fit([X_train_full_trimmed, X_train_windows], y_train_windows, epochs=10, batch_size=32,
                    validation_data=([X_test_full_trimmed, X_test_windows], y_test_windows),
                    class_weight=class_weights_dict)

# Evaluate the model using the trimmed test data
test_loss, test_accuracy = model.evaluate([X_test_full_trimmed, X_test_windows], y_test_windows)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

# Plot training & validation accuracy values
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(loc='upper left')

# Make predictions on the test set using the trimmed test data
y_pred = model.predict([X_test_full_trimmed, X_test_windows])

# Convert predicted probabilities to binary predictions (0 or 1)
y_pred = (y_pred > 0.5).astype(int)

# Print classification report
print("Classification Report:")
print(classification_report(y_test_windows, y_pred))

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test_windows, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Calculate accuracy
accuracy = np.mean(y_pred.flatten() == y_test_windows)
print(f"Accuracy: {accuracy:.4f}")
precision = precision_score(y_test_windows, y_pred)
recall = recall_score(y_test_windows, y_pred)
f1 = f1_score(y_test_windows, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

# Define the LSTM-GRU model
model_lstm_gru = models.Sequential()

# LSTM Branch (Full dataset without time-series windows)
lstm_input = Input(shape=(X_train_full.shape[1],))  # Shape of full dataset (no time-series windows)
lstm_branch = layers.Reshape((X_train_full.shape[1], 1))(lstm_input)  # Reshape for LSTM input
lstm_branch = layers.LSTM(16)(lstm_branch)  # Reduce LSTM units to 16
lstm_branch = layers.Dropout(0.8)(lstm_branch)

# GRU Branch (Full dataset, same as LSTM)
gru_input = Input(shape=(X_train_full.shape[1],))  # Same shape as the LSTM input
gru_branch = layers.Reshape((X_train_full.shape[1], 1))(gru_input)  # Reshape for GRU input
gru_branch = layers.GRU(16)(gru_branch)  # Reduce GRU units to 16
gru_branch = layers.Dropout(0.8)(gru_branch)

# Concatenate LSTM and GRU branches
merged = Concatenate()([lstm_branch, gru_branch])

# Fully connected layers
merged = layers.Dense(32, activation='relu')(merged)  # Reduce Dense layer units to 32
merged = layers.Dropout(0.8)(merged)  # Increase dropout to 0.8
output = layers.Dense(1, activation='sigmoid')(merged)

# Create the model
model_lstm_gru = Model(inputs=[lstm_input, gru_input], outputs=output)

# Compile the model
model_lstm_gru.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


# Split the data into training and testing sets
# Split the data into training and testing sets
X_train_full, X_test_full, y_train_full, y_test_full = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Print shapes after splitting
print(f"X_train_full shape: {X_train_full.shape}, y_train_full shape: {y_train_full.shape}")
print(f"X_test_full shape: {X_test_full.shape}, y_test_full shape: {y_test_full.shape}")

# Ensure matching sizes by trimming
min_samples = min(len(X_train_full), len(y_train_full))
X_train_full = X_train_full[:min_samples]
y_train_full = y_train_full[:min_samples]

# Set class weights equally to reduce impact of imbalance
class_weights_dict = {0: 1.0, 1: 1.0}

# Do the same for test sets
min_samples_test = min(len(X_test_full), len(y_test_full))

X_test_full = X_test_full[:min_samples_test]
y_test_full = y_test_full[:min_samples_test]

# Train the model (using the full dataset for both LSTM and GRU)
history = model_lstm_gru.fit([X_train_full, X_train_full], y_train_full, epochs=20, batch_size=128,  # Reduced epochs, increased batch size
                             validation_data=([X_test_full, X_test_full], y_test_full),
                             class_weight=class_weights_dict)

# Evaluate the model
test_loss, test_accuracy = model_lstm_gru.evaluate([X_test_full, X_test_full], y_test_full)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

# Make predictions (using both LSTM and GRU branches, full dataset)
y_pred = (model_lstm_gru.predict([X_test_full, X_test_full]) > 0.5).astype(int)

# Calculate precision, recall, f1-score from the classification report
report = classification_report(y_test_full, y_pred, output_dict=True)

# Extract metrics from the report
lstm_gru_accuracy = report['accuracy']  # Overall accuracy
lstm_gru_precision = report['1']['precision']  # Precision for class 1 (seizure)
lstm_gru_recall = report['1']['recall']        # Recall for class 1 (seizure)
lstm_gru_f1 = report['1']['f1-score']          # F1-score for class 1 (seizure)
lstm_gru_loss = test_loss                       # Loss from evaluation

# Print the results
print(f"LSTM-GRU Model - Accuracy: {lstm_gru_accuracy}")
print(f"LSTM-GRU Model - Precision (Seizure): {lstm_gru_precision}")
print(f"LSTM-GRU Model - Recall (Seizure): {lstm_gru_recall}")
print(f"LSTM-GRU Model - F1-Score (Seizure): {lstm_gru_f1}")
print(f"LSTM-GRU Model - Test Loss: {lstm_gru_loss}")

# Plot the confusion matrix
conf_matrix = confusion_matrix(y_test_full, y_pred)

# Plotting the confusion matrix
plt.figure(figsize=(6, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap=plt.cm.Blues, xticklabels=['Non-Seizure (0)', 'Seizure (1)'],
            yticklabels=['Non-Seizure (0)', 'Seizure (1)'], cbar=True)

# Add labels and title
plt.title('Confusion Matrix')
plt.ylabel('True label')
plt.xlabel('Predicted label')

# Show the plot
plt.show()

df = pd.read_csv('/content/Epileptic Seizure Recognition.csv')

# Drop the 'Unnamed' column, which isn't necessary for the model
df = df.drop(columns=['Unnamed'], errors='ignore')

df['y'] = df['y'].apply(lambda x: 1 if x == 1 else 0)

# Separate features and labels
X = df.drop(columns=['y']).values  # Features (input EEG signals)
y = df['y'].values  # Labels (0 = non-seizure, 1 = seizure)

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Print the shape of the scaled features
print(f"Scaled features shape: {X_scaled.shape}")

X_train_full, X_test_full, y_train_full, y_test_full = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report
from sklearn.utils import class_weight

# Assuming X_train_full, X_test_full, y_train_full, y_test_full are already defined

# Compute class weights to handle class imbalance
class_weights = class_weight.compute_class_weight(class_weight='balanced', classes=np.unique(y_train_full), y=y_train_full)
class_weights_dict = {i: class_weights[i] for i in range(len(class_weights))}
print("Class weights:", class_weights_dict)

# Build the enhanced LSTM-BERT model with regularization and adjustments to reduce overfitting
model_lstm_bert = models.Sequential()

# Input layer with batch normalization
model_lstm_bert.add(layers.InputLayer(input_shape=(X_train_full.shape[1],)))
model_lstm_bert.add(layers.BatchNormalization())

# BERT-like Dense embedding with batch normalization, dropout, and L2 regularization
model_lstm_bert.add(layers.Dense(256, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model_lstm_bert.add(layers.BatchNormalization())
model_lstm_bert.add(layers.Dropout(0.6))  # Increased dropout rate to 0.6 for more regularization

# Reshape for LSTM layers (reshape to (timesteps, features) for LSTM input)
model_lstm_bert.add(layers.Reshape((1, 256)))  # Here, (1, 256) is just an example shape

# First Bidirectional LSTM layer with L2 regularization
model_lstm_bert.add(layers.Bidirectional(layers.LSTM(128, return_sequences=True, kernel_regularizer=tf.keras.regularizers.l2(0.01))))
model_lstm_bert.add(layers.Dropout(0.6))  # Increased dropout rate

# Second Bidirectional LSTM layer with L2 regularization
model_lstm_bert.add(layers.Bidirectional(layers.LSTM(128, return_sequences=False, kernel_regularizer=tf.keras.regularizers.l2(0.01))))
model_lstm_bert.add(layers.Dropout(0.6))  # Increased dropout rate

# Dense layer for attention-like mechanism
model_lstm_bert.add(layers.Dense(128, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model_lstm_bert.add(layers.Dropout(0.5))  # Dropout to further regularize

# Output layer for binary classification
model_lstm_bert.add(layers.Dense(1, activation='sigmoid'))

# Compile the model with a learning rate scheduler and a smaller initial learning rate
initial_learning_rate = 0.0005  # Lower initial learning rate
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate, decay_steps=100000, decay_rate=0.96, staircase=True)

model_lstm_bert.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule),
                        loss='binary_crossentropy', metrics=['accuracy'])

# Early stopping callback to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=6, restore_best_weights=True)

# Train the model with class weights and callbacks
history_lstm_bert = model_lstm_bert.fit(
    X_train_full, y_train_full, epochs=20, batch_size=64, validation_split=0.2,
    class_weight=class_weights_dict, callbacks=[early_stopping]
)

# Evaluate the improved model
test_loss_bert, test_accuracy_bert = model_lstm_bert.evaluate(X_test_full, y_test_full)
print(f"Enhanced LSTM-BERT Test Loss: {test_loss_bert}, Test Accuracy: {test_accuracy_bert}")

# Predictions and classification report
y_pred_bert = (model_lstm_bert.predict(X_test_full) > 0.5).astype(int)
report_bert = classification_report(y_test_full, y_pred_bert, output_dict=True)

# Extract metrics
lstm_bert_accuracy = report_bert['accuracy']
lstm_bert_precision = report_bert['1']['precision']
lstm_bert_recall = report_bert['1']['recall']
lstm_bert_f1 = report_bert['1']['f1-score']

# Print enhanced model metrics
print(f"Enhanced LSTM-BERT Accuracy: {lstm_bert_accuracy:.4f}")
print(f"Enhanced LSTM-BERT Precision: {lstm_bert_precision:.4f}")
print(f"Enhanced LSTM-BERT Recall: {lstm_bert_recall:.4f}")
print(f"Enhanced LSTM-BERT F1 Score: {lstm_bert_f1:.4f}")

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report
from sklearn.utils import class_weight

# Compute class weights to handle class imbalance
class_weights = class_weight.compute_class_weight(class_weight='balanced', classes=np.unique(y_train_full), y=y_train_full)
class_weights_dict = {i: class_weights[i] for i in range(len(class_weights))}
print("Class weights:", class_weights_dict)

# Build the GRU model
model_gru = models.Sequential()

# Input layer with batch normalization
model_gru.add(layers.Input(shape=(X_train_full.shape[1],)))  # Use 'shape' instead of 'input_shape'
model_gru.add(layers.BatchNormalization())

# Dense layer with batch normalization and increased dropout
model_gru.add(layers.Dense(64, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)))  # Reduced units to prevent overfitting
model_gru.add(layers.BatchNormalization())
model_gru.add(layers.Dropout(0.6))  # Increased dropout rate

# Reshape the input to 3D (timesteps, features)
model_gru.add(layers.Reshape((1, 64)))  # Reshaping to (timesteps=1, features=64)

# GRU layer with regularization
model_gru.add(layers.GRU(64, return_sequences=False, kernel_regularizer=tf.keras.regularizers.l2(0.01)))  # Reduced GRU units
model_gru.add(layers.Dropout(0.6))  # Increased dropout rate after GRU layer

# Dense layer for additional processing
model_gru.add(layers.Dense(32, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)))  # Reduced units
model_gru.add(layers.Dropout(0.5))  # Dropout

# Output layer for binary classification
model_gru.add(layers.Dense(1, activation='sigmoid'))

# Compile the model with a learning rate scheduler
initial_learning_rate = 0.0001  # Reduced initial learning rate
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate, decay_steps=100000, decay_rate=0.96, staircase=True)

model_gru.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule),
                  loss='binary_crossentropy', metrics=['accuracy'])

# Early stopping callback to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Train the model with class weights and callbacks
history_gru = model_gru.fit(
    X_train_full, y_train_full, epochs=20, batch_size=64, validation_split=0.2,
    class_weight=class_weights_dict, callbacks=[early_stopping]
)

# Evaluate the model
test_loss_gru, test_accuracy_gru = model_gru.evaluate(X_test_full, y_test_full)
print(f"GRU Test Loss: {test_loss_gru}, Test Accuracy: {test_accuracy_gru}")

# Predictions and classification report
y_pred_gru = (model_gru.predict(X_test_full) > 0.5).astype(int)
report_gru = classification_report(y_test_full, y_pred_gru, output_dict=True)

# Extract metrics
gru_accuracy = report_gru['accuracy']
gru_precision = report_gru['1']['precision']
gru_recall = report_gru['1']['recall']
gru_f1 = report_gru['1']['f1-score']

# Print GRU model metrics
print(f"GRU Accuracy: {gru_accuracy:.4f}")
print(f"GRU Precision: {gru_precision:.4f}")
print(f"GRU Recall: {gru_recall:.4f}")
print(f"GRU F1 Score: {gru_f1:.4f}")

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report
from sklearn.utils import class_weight

# Assuming X_train_full, X_test_full, y_train_full, y_test_full are already defined

# Compute class weights to handle class imbalance
class_weights = class_weight.compute_class_weight(class_weight='balanced', classes=np.unique(y_train_full), y=y_train_full)
class_weights_dict = {i: class_weights[i] for i in range(len(class_weights))}
print("Class weights:", class_weights_dict)

# Build the RNN model with further overfitting reduction techniques
model_rnn = models.Sequential()

# Input layer with batch normalization
model_rnn.add(layers.Input(shape=(X_train_full.shape[1],)))  # Use 'shape' instead of 'input_shape'
model_rnn.add(layers.BatchNormalization())

# Dense layer with batch normalization and increased dropout
model_rnn.add(layers.Dense(32, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)))  # Reduced units further
model_rnn.add(layers.BatchNormalization())
model_rnn.add(layers.Dropout(0.7))  # Increased dropout rate further

# Reshape the input to 3D (timesteps, features) for RNN
model_rnn.add(layers.Reshape((1, 32)))  # Reshaping to (timesteps=1, features=32)

# RNN layer with regularization
model_rnn.add(layers.SimpleRNN(32, return_sequences=False, kernel_regularizer=tf.keras.regularizers.l2(0.01)))  # Using RNN layer
model_rnn.add(layers.Dropout(0.7))  # Increased dropout rate after RNN layer

# Dense layer for additional processing
model_rnn.add(layers.Dense(16, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)))  # Reduced units further
model_rnn.add(layers.Dropout(0.6))  # Increased dropout rate

# Output layer for binary classification
model_rnn.add(layers.Dense(1, activation='sigmoid'))

# Compile the model with a learning rate scheduler
initial_learning_rate = 0.00005  # Reduced learning rate further
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate, decay_steps=100000, decay_rate=0.96, staircase=True)

model_rnn.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule),
                  loss='binary_crossentropy', metrics=['accuracy'])

# Early stopping callback to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)  # More aggressive early stopping

# Train the model with class weights and callbacks
history_rnn = model_rnn.fit(
    X_train_full, y_train_full, epochs=20, batch_size=64, validation_split=0.2,
    class_weight=class_weights_dict, callbacks=[early_stopping]
)

# Evaluate the model
test_loss_rnn, test_accuracy_rnn = model_rnn.evaluate(X_test_full, y_test_full)
print(f"RNN Test Loss: {test_loss_rnn}, Test Accuracy: {test_accuracy_rnn}")

# Predictions and classification report
y_pred_rnn = (model_rnn.predict(X_test_full) > 0.5).astype(int)
report_rnn = classification_report(y_test_full, y_pred_rnn, output_dict=True)

# Extract metrics
rnn_accuracy = report_rnn['accuracy']
rnn_precision = report_rnn['1']['precision']
rnn_recall = report_rnn['1']['recall']
rnn_f1 = report_rnn['1']['f1-score']

# Print RNN model metrics
print(f"RNN Accuracy: {rnn_accuracy:.4f}")
print(f"RNN Precision: {rnn_precision:.4f}")
print(f"RNN Recall: {rnn_recall:.4f}")
print(f"RNN F1 Score: {rnn_f1:.4f}")

import pandas as pd
import matplotlib.pyplot as plt

# Compare the accuracy, precision, recall, and F1 score of the five models

# LSTM-CNN Metrics
lstm_cnn_accuracy = history.history['accuracy'][-1]   # Accuracy from the last epoch
lstm_cnn_precision = precision
lstm_cnn_recall = recall
lstm_cnn_f1 = f1_score

# LSTM-GRU Metrics
lstm_gru_accuracy = report['accuracy']  # Accuracy from classification report
lstm_gru_precision = report['1']['precision']  # Precision for class 1 (seizure)
lstm_gru_recall = report['1']['recall']  # Recall for class 1 (seizure)
lstm_gru_f1 = report['1']['f1-score']  # F1-score for class 1 (seizure)

# LSTM-BERT Metrics
lstm_bert_accuracy = report_bert['accuracy']
lstm_bert_precision = report_bert['1']['precision']
lstm_bert_recall = report_bert['1']['recall']
lstm_bert_f1 = report_bert['1']['f1-score']

# GRU Metrics
gru_accuracy = report_gru['accuracy']
gru_precision = report_gru['1']['precision']
gru_recall = report_gru['1']['recall']
gru_f1 = report_gru['1']['f1-score']

# RNN Metrics
rnn_accuracy = report_rnn['accuracy']
rnn_precision = report_rnn['1']['precision']
rnn_recall = report_rnn['1']['recall']
rnn_f1 = report_rnn['1']['f1-score']

# Create a DataFrame to display the comparison
comparison_df = pd.DataFrame({
    'Model': ['LSTM-CNN', 'LSTM-GRU', 'LSTM-BERT', 'GRU', 'RNN'],
    'Accuracy': [lstm_cnn_accuracy, lstm_gru_accuracy, lstm_bert_accuracy, gru_accuracy, rnn_accuracy],
    'Precision': [lstm_cnn_precision, lstm_gru_precision, lstm_bert_precision, gru_precision, rnn_precision],
    'Recall': [lstm_cnn_recall, lstm_gru_recall, lstm_bert_recall, gru_recall, rnn_recall],
    'F1 Score': [lstm_cnn_f1, lstm_gru_f1, lstm_bert_f1, gru_f1, rnn_f1]
})

# Display the comparison table
print(comparison_df)

# Plotting Bar Plot
fig, axes = plt.subplots(2, 1, figsize=(12, 12))

comparison_df.set_index('Model').plot(kind='bar', ax=axes[0])
axes[0].set_title('Comparison of LSTM-CNN, LSTM-GRU, LSTM-BERT, GRU, and RNN Models')
axes[0].set_ylabel('Scores')
axes[0].set_xticklabels(comparison_df['Model'], rotation=0)

# Plotting Line Plot
comparison_df.set_index('Model').plot(kind='line', marker='o', ax=axes[1])
axes[1].set_title('Comparison of LSTM-CNN, LSTM-GRU, LSTM-BERT, GRU, and RNN Models')
axes[1].set_ylabel('Scores')
axes[1].set_xticks(range(len(comparison_df)))
axes[1].set_xticklabels(comparison_df['Model'], rotation=0)

# Tight layout to prevent overlap
plt.tight_layout()
plt.show()

